apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: benchmark-logs
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 6
  replicas: 3
  config:
    # OTIMIZAÇÃO DE RECURSOS:
    retention.ms: 7200000       # Mantém dados por apenas 2 horas (economiza disco)
    segment.bytes: 1073741824   # Segmentos de 1GB