apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-resources-metrics
  namespace: monitoring
  labels:
    release: prometheus
    app: strimzi
spec:
  selector:
    matchExpressions:
      - key: "strimzi.io/kind"
        operator: In
        values: ["Kafka", "ZooKeeper"]
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
  - path: /metrics
    port: tcp-prometheus
    interval: 10s
    # --- A M√ÅGICA ACONTECE AQUI ---
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_label_strimzi_io_cluster]
      targetLabel: strimzi_io_cluster
    - sourceLabels: [__meta_kubernetes_pod_label_strimzi_io_kind]
      targetLabel: strimzi_io_kind
    - sourceLabels: [__meta_kubernetes_pod_label_strimzi_io_name]
      targetLabel: strimzi_io_name